name: prueba_tecnica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

 # Local Database
  isar: ^3.1.0+1
  path_provider: ^2.1.1
  isar_flutter_libs: ^3.0.0

  #STATES MANAGEMENT
  flutter_riverpod: ^2.3.6
  hooks_riverpod: ^2.3.7
  flutter_hooks: ^0.20.5
  provider: ^6.1.2

  #ROUTER
  go_router: ^14.6.0
  
  # UI UTILITY
  animate_do: ^3.3.3

  # UTILS
  shared_preferences: ^2.2.0
  flutter_dotenv: ^5.1.0
  dio: ^5.3.0
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0

  #LOADING
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  analyzer: ^5.13.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
  - .env
